version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DB_URL}
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    command: >
      sh -c "pnpm exec drizzle-kit migrate &&
             pnpm run start:prod"

volumes:
  postgres-data:
